"""initial schema

Revision ID: 8bfd0e7a05f2
Revises: 
Create Date: 2026-06-01 05:16:38.185474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bfd0e7a05f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key_hash')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_company_id'), ['company_id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_results_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_results_tender_id'), ['tender_id'], unique=False)

    op.create_table('tenders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title_he', sa.String(), nullable=False),
    sa.Column('publisher_he', sa.String(), nullable=True),
    sa.Column('source_pdf', sa.String(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenders')
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_results_tender_id'))
        batch_op.drop_index(batch_op.f('ix_match_results_company_id'))

    op.drop_table('match_results')
    op.drop_table('companies')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_company_id'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
