"""add_contract_dates_status_fields

Revision ID: a95442197cae
Revises: a1f3c9d2e841
Create Date: 2026-06-02 13:22:02.818374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95442197cae'
down_revision: Union[str, Sequence[str], None] = 'a1f3c9d2e841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_tenders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tender_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('decision', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tender_type_he', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contract_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contract_end', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_tenders', schema=None) as batch_op:
        batch_op.drop_column('contract_end')
        batch_op.drop_column('contract_start')
        batch_op.drop_column('tender_type_he')
        batch_op.drop_column('decision')
        batch_op.drop_column('tender_status')

    # ### end Alembic commands ###
