"""add raw_tenders table

Revision ID: cdc3c5ceff3a
Revises: 8bfd0e7a05f2
Create Date: 2026-06-01 10:14:09.135047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc3c5ceff3a'
down_revision: Union[str, Sequence[str], None] = '8bfd0e7a05f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_tenders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('title_he', sa.String(), nullable=True),
    sa.Column('publisher_he', sa.String(), nullable=True),
    sa.Column('subjects_json', sa.Text(), nullable=True),
    sa.Column('tender_type', sa.String(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('estimated_budget_ils', sa.Float(), nullable=True),
    sa.Column('pdf_urls_json', sa.Text(), nullable=True),
    sa.Column('pdf_blob', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('raw_metadata_json', sa.Text(), nullable=True),
    sa.Column('harvested_at', sa.String(), nullable=True),
    sa.Column('analyzed_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_tenders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_tenders_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_tenders_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_tenders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_tenders_uploaded_by'), ['uploaded_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_tenders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_tenders_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_raw_tenders_status'))
        batch_op.drop_index(batch_op.f('ix_raw_tenders_source_id'))
        batch_op.drop_index(batch_op.f('ix_raw_tenders_external_id'))

    op.drop_table('raw_tenders')
    # ### end Alembic commands ###
