"""add_rejection_reason

Revision ID: e46f72fc3054
Revises: a95442197cae
Create Date: 2026-06-02 13:44:08.178667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46f72fc3054'
down_revision: Union[str, Sequence[str], None] = 'a95442197cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_tenders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_tenders', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')

    # ### end Alembic commands ###
